### PR TITLE
Udpate out-date code

### PR DESCRIPTION
**Pull request by Oliverwqcwrw**
I notice some out-date code in `nacos`, so I have updated to the latest

### CODE REVIEW

**Comment by yanglbme** [comment]
There are some problems in code indent, please fix it

> 代码缩进有些问题，可以改一下

**Comment by Oliverwqcwrw** [comment]
Ok,I will solve it

**Comment by Oliverwqcwrw** [comment]
I have formated it ,please check if have other issue

**Comment by yanglbme** [comment]
image

@Oliverwqcwrw

**Comment by Oliverwqcwrw** [comment]
Ok

**Comment by Oliverwqcwrw** [comment]
PTAL

**Comment by yanglbme** [comment]
@Oliverwqcwrw please move code to the left

image

**Comment by Oliverwqcwrw** [comment]
Ok,Thanks for your checking

**Comment by Oliverwqcwrw** [comment]
I have moved it to left

**Comment by yanglbme** [comment]
@Oliverwqcwrw Thanks for your contribution.

**Pull request merged**
